sudo: false
language: python
python:
  - 3.4
  - 3.5
  - 3.6

install:
  - pip3 install -r requirements/install.txt requirements/develop.txt
  - pip3 install .

script:
  - py.test --cov-config .coveragerc --cov=automaton

after_success:
  - bash <(curl -s https://codecov.io/bash)
