sudo: false
language: python
python:
  - 3.4
  - 3.5
  - 3.6

install:
  - pip3 install pytest
  - pip3 install pytest-cov
  - pip3 install codecov

script:
  - py.test --cov=./

after_success:
  - codecov
