sudo: false
language: python
python:
  - 3.4
  - 3.5
  - 3.6

install:
  - pip3 install -r requirements/install.txt -r requirements/develop.txt
  # editable install (-e) is required, otherwise we're going to face this:
  # 'Coverage.py warning: No data was collected.'
  # https://github.com/pytest-dev/pytest-cov/issues/98
  - pip3 install -e .

script:
  - py.test --cov-config .coveragerc --cov=automaton

after_success:
  - bash <(curl -s https://codecov.io/bash)
